set dotenv-load

build:
  forge build

test:
  forge test

deploy WHAT:
  forge create --rpc-url $RPC_URL \
    --private-key $PRIVATE_KEY {{ WHAT }} \
    --etherscan-api-key $ETHERSCAN_API_KEY FKJZBUYA8JBZGRNAE7RGDZT23ZVSTCD3DC \
    --verify