import { Article } from "../interfaces";


const mockArticles: Article[] = [
    {
        id: "a1",
        title: "Tech Trends: AI in 2023",
        publicationId: "1",
        summary: "A detailed analysis of how AI is transforming industries in 2023.",
        image: "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg",
        author: "John Doe",
        authorImage: "https://images.pexels.com/photos/123123/author1.jpeg",
        content: "Artificial Intelligence has been the buzzword for the last decade, transforming numerous industries, including healthcare, finance, retail, and more. It's not just about automated tasks anymore, but about solving complex problems, predicting human behavior, and personalizing experiences. This year, the trends indicate a focus on ethical AI, reinforcement learning, and more practical, scalable AI implementations.",
        publishDate: "2023-06-01",
    },
    {
        id: "a2",
        title: "Interview with Tech Innovator Jane Smith",
        publicationId: "1",
        summary: "Jane Smith shares her journey and the future of her tech startup.",
        image: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg",
        author: "Sarah Lee",
        authorImage: "https://images.pexels.com/photos/123124/author2.jpeg",
        content: "In a world dominated by tech giants, Jane Smith is carving a niche with her innovative startup. We caught up with her to talk about her journey, the challenges she faced, and how she is leveraging technology to bring a change. She shares insights on how the startup ecosystem has evolved and what young entrepreneurs need to succeed.",
        publishDate: "2023-05-15",
    },
    {
        id: "a3",
        title: "Cryptocurrency: The Future of Finance?",
        publicationId: "1",
        summary: "Exploring the potential of cryptocurrency to replace traditional financial systems.",
        image: "https://images.pexels.com/photos/730547/pexels-photo-730547.jpeg",
        author: "Tom Johnson",
        authorImage: "https://images.pexels.com/photos/123125/author3.jpeg",
        content: "Cryptocurrency has been on a rollercoaster ride since its inception. With high volatility and regulatory scrutiny, it continues to be a topic of heated debate. Yet, with more acceptance from businesses and a surge in consumer interest, could cryptocurrency be the future of finance? This article dives deep into the possibilities and challenges.",
        publishDate: "2023-04-20",
    },
    {
        id: "b1",
        title: "Home Workouts: Effective or Overrated?",
        publicationId: "2",
        summary: "Analyzing the effectiveness of home workouts during the pandemic.",
        image: "https://images.pexels.com/photos/3755751/pexels-photo-3755751.jpeg",
        author: "Maria Davis",
        authorImage: "https://images.pexels.com/photos/123125/author3.jpeg",
        content: "With gyms closing during the pandemic, home workouts have become a trend. But are they as effective as gym workouts? This article explores various home workout regimes, their benefits, and how they compare to traditional gym workouts. It also delves into maintaining motivation and consistency while working out at home.",
        publishDate: "2023-06-02",
    },
    {
        id: "b2",
        title: "Nutrition Myths Busted",
        publicationId: "2",
        summary: "Scientific truths about some of the most common nutrition myths.",
        image: "https://images.pexels.com/photos/3764642/pexels-photo-3764642.jpeg",
        author: "Lisa Chen",
        authorImage: "https://images.pexels.com/photos/123125/author3.jpeg",
        content: "Healthy eating can be confusing with the multitude of nutrition myths floating around. Is gluten really bad? Are all fats unhealthy? Do you need to detox your body regularly? We dive into these questions and more, backed by scientific evidence to set the facts straight.",
        publishDate: "2023-05-18",
    },
    {
        id: "b3",
        title: "Yoga: A Journey Within",
        publicationId: "2",
        summary: "The transformative power of Yoga and its global popularity.",
        image: "https://images.pexels.com/photos/1812964/pexels-photo-1812964.jpeg",
        author: "Gary Taylor",
        authorImage: "https://images.pexels.com/photos/123125/author3.jpeg",
        content: "Yoga, an ancient practice from India, has become a global phenomenon. It's not just about physical fitness but also mental well-being. The article delves into the journey of yoga from East to West, its health benefits, and its power to transform lives. It also provides insights into different yoga styles and how to get started with the practice.",
        publishDate: "2023-05-05",
    },
    {
        id: "c1",
        title: "Italian Cuisine: Beyond Pizza and Pasta",
        publicationId: "3",
        summary: "Exploring the rich and varied gastronomy of Italy.",
        image: "https://images.pexels.com/photos/3026806/pexels-photo-3026806.jpeg",
        author: "Laura Miller",
        authorImage: "https://images.pexels.com/photos/123125/author3.jpeg",
        content: "When we think about Italian cuisine, pizza and pasta are the first things that come to mind. But Italian cuisine is much more diverse, with a rich culinary history spanning thousands of years and differing vastly from the north to the south. This article explores the lesser-known aspects of Italian gastronomy, taking you on a culinary tour of Italy.",
        publishDate: "2023-06-08",
    },
    {
        id: "c2",
        title: "A Culinary Tour of France",
        publicationId: "3",
        summary: "A mouth-watering journey through the culinary delights of France.",
        image: "https://images.pexels.com/photos/209709/pexels-photo-209709.jpeg",
        author: "Alice Martin",
        authorImage: "https://images.pexels.com/photos/123125/author3.jpeg",
        content: "French cuisine is renowned worldwide, a gastronomic delight that ranges from the rustic dishes of the countryside to the haute cuisine of Paris. With regional specialties and dishes steeped in history, this article takes you on a culinary journey through France, exploring its diverse food culture.",
        publishDate: "2023-05-28",
    },
    {
        id: "c3",
        title: "The Art of Sushi Making",
        publicationId: "3",
        summary: "The history, culture, and technique behind making sushi.",
        image: "https://images.pexels.com/photos/2253810/pexels-photo-2253810.jpeg",
        author: "William Brown",
        authorImage: "https://images.pexels.com/photos/123125/author3.jpeg",
        content: "Sushi, the iconic dish of Japan, is much more than a meal; it's an art form. This article explores the history of sushi, how it's deeply entwined with Japanese culture and tradition, and the intricate technique involved in sushi making. From choosing the right fish to the precision of rolling, learn the art behind this Japanese delicacy.",
        publishDate: "2023-05-12",
    },
    // More articles for other publications (d1, d2, d3, e1, e2, e3) following a similar pattern...
];

export default mockArticles;